import java.util.Scanner;
import java.text.DecimalFormat;
/**
 * Compute the value for the varaiable x
 * generated by a specified formula.
 */
public class RadicalFormula {
   /** 
    * @param args - Standard commandline arguments
    *
    * @author Austin Keelin
    * @version 02/03/2016   
    *
    */
   public static void main(String[] args) {
   
      Scanner userInput = new Scanner(System.in);
      double x = 0;
      double firstHalf = 0;
      double firstHalfSquared;
      double secondHalf = 0;
      double main = 0;
      double result = 0;
      int decimal = 0;
      int length = 0;
      int decimalLeft = 0;
      int decimalRight = 0;
      
      System.out.print("Enter a value " 
         + "for x: ");
      x = userInput.nextDouble();
      
      System.out.print("Result: ");
      firstHalf = (3 * Math.pow(x, 8) - 2 * Math.pow(x, 3));
      firstHalfSquared = Math.pow(firstHalf, 2);
      secondHalf = (Math.abs(3 * Math.pow(x, 5) - 2 * Math.pow(x, 3)));
      main = firstHalfSquared + secondHalf;
      result = Math.sqrt(main);
      System.out.println(result);
      
      System.out.print("# digits to left "
         + "of decimal point: ");
      String stringResult = Double.toString(result);
      decimal = stringResult.indexOf(".");
      length = stringResult.length() - 1;
      decimalRight = length - decimal;
      decimalLeft = length - decimalRight;
      System.out.println(decimalLeft);
      
      System.out.print("# digits to right "
         + "of decimal point: ");
      System.out.println(decimalRight);
      
      DecimalFormat decimalFmt = new DecimalFormat("#,##0.0##");
      System.out.print("Formatted Result: "
         + decimalFmt.format(result));
      
   }
}